"""
Tests for Virtual Memory Card creation and assignment.

Run from the romen-ps2-server directory:

    python tests/test_vmc.py

These cover the memory card binary format, which is the part of ISObe where a
mistake costs someone their saves rather than just a bad filename. The expected
superblock values for an 8MB card are the published values for a real PS2
memory card, so a regression here shows up as a concrete mismatch.
"""

import os
import sys
import shutil
import tempfile
from array import array

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import system
import vmc

FAILURES = []


def check(label, got, want):
    if got == want:
        print(f"  ok   {label}")
    else:
        print(f"  FAIL {label}: got {got!r}, expected {want!r}")
        FAILURES.append(label)


def section(name):
    print(f"\n{name}")


def test_superblock_8mb(tmp):
    section("8MB card matches a real PS2 memory card")
    path = os.path.join(tmp, "eight.bin")
    vmc._write_formatted_card(path, 8)

    check("file size", os.path.getsize(path), 8388608)

    with open(path, "rb") as f:
        sb = vmc._SUPERBLOCK.unpack(f.read(vmc._SUPERBLOCK.size))
    (magic, version, page_size, pages_per_cluster, pages_per_block, unused,
     clusters_per_card, alloc_offset, alloc_end, rootdir, gb1, gb2,
     ifc, bad, card_type, card_flags) = sb

    check("magic", magic, b"Sony PS2 Memory Card Format ")
    check("version", version.split(b"\x00")[0], b"1.2.0.0")
    check("page size", page_size, 512)
    check("pages per cluster", pages_per_cluster, 2)
    check("pages per erase block", pages_per_block, 16)
    check("clusters per card", clusters_per_card, 8192)
    check("allocatable offset", alloc_offset, 41)
    check("allocatable end", alloc_end, 8135)
    check("root directory cluster", rootdir, 0)
    check("good block 1", gb1, 1023)
    check("good block 2", gb2, 1022)
    check("card type", card_type, 2)

    ifc_list = array("I")
    ifc_list.frombytes(ifc)
    check("first indirect FAT cluster", ifc_list[0], 8)

    # This is the exact test OPL applies in sysCheckVMC(). A card that fails it
    # is silently deleted and regenerated by the console.
    check("OPL size equation",
          os.path.getsize(path),
          pages_per_cluster * clusters_per_card * page_size)

    with open(path, "rb") as f:
        f.seek(8 * vmc.CLUSTER_SIZE)
        indirect = array("I")
        indirect.frombytes(f.read(vmc.CLUSTER_SIZE))
        f.seek(9 * vmc.CLUSTER_SIZE)
        fat = array("I")
        fat.frombytes(f.read(vmc.CLUSTER_SIZE))

    check("indirect FAT points at FAT clusters", list(indirect[:32]), list(range(9, 41)))
    check("indirect FAT terminates", indirect[32], 0xFFFFFFFF)
    check("root dir cluster allocated", fat[0], vmc.FAT_CHAIN_END)
    check("second cluster free", fat[1], vmc.FAT_FREE)


def test_all_sizes(tmp):
    section("every offered size formats to a card OPL accepts")
    for size_mb in vmc.VALID_SIZES_MB:
        path = os.path.join(tmp, f"card{size_mb}.bin")
        vmc._write_formatted_card(path, size_mb)
        size = os.path.getsize(path)
        with open(path, "rb") as f:
            sb = vmc._SUPERBLOCK.unpack(f.read(vmc._SUPERBLOCK.size))
        page_size, pages_per_cluster, clusters_per_card = sb[2], sb[3], sb[6]
        check(f"{size_mb}MB size", size, size_mb * 1024 * 1024)
        check(f"{size_mb}MB OPL size equation", size,
              pages_per_cluster * clusters_per_card * page_size)
        check(f"{size_mb}MB whole megabytes", size % 1048576, 0)
        check(f"{size_mb}MB reported valid", vmc.inspect_vmc(path)["valid"], True)
        os.remove(path)


def test_create_api(tmp):
    section("create rejects bad input and stays inside the VMC folder")
    check("valid card created", vmc.create_vmc("GOOD", 8)["status"], "success")
    check("duplicate refused", vmc.create_vmc("GOOD", 8)["status"], "error")
    check("bad size refused", vmc.create_vmc("ODD", 12)["status"], "error")
    check("empty name refused", vmc.create_vmc("   ", 8)["status"], "error")

    # A name containing path separators must not escape the VMC directory.
    vmc.create_vmc("../../escape", 8)
    escaped = os.path.join(tmp, "escape.bin")
    check("no file written outside VMC folder", os.path.exists(escaped), False)
    check("traversal collapsed to a plain name",
          os.path.exists(os.path.join(tmp, "VMC", "escape.bin")), True)


def test_cfg_assignment(tmp):
    section("assignment preserves the rest of the game's config")
    cfg_dir = os.path.join(tmp, "CFG")
    os.makedirs(cfg_dir, exist_ok=True)
    cfg = os.path.join(cfg_dir, "SLUS_200.02.cfg")
    original = (b"$ConfigSource=1\r\nTitle=Metal Gear Solid 2\r\n"
                b"$Genre=Action\r\n$Compatibility=1\r\n")
    with open(cfg, "wb") as f:
        f.write(original)

    vmc.create_vmc("CARD", 8)
    check("assign succeeds", vmc.assign_vmc("SLUS_200.02", "CARD", 0)["status"], "success")

    with open(cfg, "rb") as f:
        after = f.read()
    check("existing keys untouched", after.startswith(original), True)
    check("slot key appended", b"$VMC_0=CARD\r\n" in after, True)
    check("CRLF line endings", after.count(b"\r\n"), after.count(b"\n"))
    check("read back", vmc.get_assignments("SLUS_200.02")[0], "CARD")

    # Reassigning must replace the key, not add a second one.
    vmc.create_vmc("OTHER", 8)
    vmc.assign_vmc("SLUS_200.02", "OTHER", 0)
    with open(cfg, "rb") as f:
        after = f.read()
    check("only one slot key", after.count(b"$VMC_0="), 1)
    check("slot updated", vmc.get_assignments("SLUS_200.02")[0], "OTHER")

    check("missing card refused", vmc.assign_vmc("SLUS_200.02", "NOPE", 0)["status"], "error")
    check("bad slot refused", vmc.assign_vmc("SLUS_200.02", "CARD", 7)["status"], "error")

    vmc.unassign_vmc("SLUS_200.02", 0)
    with open(cfg, "rb") as f:
        after = f.read()
    check("unassign removes the key", b"$VMC_0" in after, False)
    check("unassign keeps the config", after, original)


def test_delete_unbinds(tmp):
    section("deleting a card unbinds it from the games using it")
    vmc.create_vmc("DOOMED", 8)
    vmc.assign_vmc("SLUS_212.81", "DOOMED", 0)
    check("bound before delete", vmc.get_assignments("SLUS_212.81")[0], "DOOMED")

    result = vmc.delete_vmc("DOOMED")
    check("delete succeeds", result["status"], "success")
    check("reported which games were freed", result["unassigned_from"], ["SLUS_212.81"])
    check("slot cleared", vmc.get_assignments("SLUS_212.81")[0], None)
    check("file gone", os.path.exists(os.path.join(tmp, "VMC", "DOOMED.bin")), False)


def test_provision_is_idempotent(tmp):
    section("auto-provision never reformats a card that already exists")
    serial = "SLUS_203.12"
    check("provisioned", vmc.provision_for_game(serial, 8)["status"], "success")

    name = vmc.name_for_serial(serial)
    path = os.path.join(tmp, "VMC", f"{name}.bin")

    # Write a marker into the card's data area, then provision again. If the
    # card were reformatted the marker would be gone along with any real saves.
    marker = b"SAVEDATA"
    with open(path, "r+b") as f:
        f.seek(41 * vmc.CLUSTER_SIZE + 1024)
        f.write(marker)

    check("provisioned again", vmc.provision_for_game(serial, 8)["status"], "success")
    with open(path, "rb") as f:
        f.seek(41 * vmc.CLUSTER_SIZE + 1024)
        check("existing card left intact", f.read(len(marker)), marker)


def main():
    tmp = tempfile.mkdtemp(prefix="isobe-vmc-test-")
    system.CONFIG.LIB_PATH = tmp
    print(f"Using temporary library at {tmp}")
    try:
        test_superblock_8mb(tmp)
        test_all_sizes(tmp)
        test_create_api(tmp)
        test_cfg_assignment(tmp)
        test_delete_unbinds(tmp)
        test_provision_is_idempotent(tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print()
    if FAILURES:
        print(f"{len(FAILURES)} check(s) failed: {', '.join(FAILURES)}")
        return 1
    print("All VMC checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
